spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_database?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  transaction:
    rollback-on-commit-failure: true
mybatis:
  mapper-locations: classpath:mapper/LogisticsMapper.xml
logging:
  file: D:/logistisc/logistisc.log