spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_database?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  transaction:
    rollback-on-commit-failure: true
  ###redis的配置
  redis:
    ###redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        ###连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ###连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ###连接池中的最大空闲连接
        max-idle: 5
        ###连接池中的最小空闲连接
        min-idle: 0
    ###连接超时时间（毫秒）
    timeout: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/LogisticsMapper.xml
logging:
  file: D:/logistisc/logistisc.log